apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: pg-stateful
spec:
  serviceName: postgres
  replicas: 3
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        imagePullPolicy: Always
        image: "postgres:9.6.2"
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name : POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: pg-stateful-config
              key: postgres_user
        - name : POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
                name: pg-stateful-config
                key: postgres_password
        - name : PGDATA
          valueFrom:
            configMapKeyRef:
                name: pg-stateful-config
                key: pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          gcePersistentDisk:
            fsType: ext4
            pdName: postgres-disk
